
app:
  site-url: https://sso.yingtaohuo.com
  #site-url: http://127.0.0.1:8081

spring:
  freemarker:
    cache: true
  
  redis:
    database: 8
    host: wx3rd.menuxx.com
    port: 7389
    password: 4cj34t4j9
    timeout: 500
    pool:
      max-active: 100
      min-idle: 100
      max-idle: 100
      max-wait: 10000


  datasource:
    password: FNQ31287twv
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.23.84.153/menuxx_prd?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql://nizhuantech.com:65321/menuxx_prd?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 30
      minimum-idle: 20
      connection-init-sql: select count(1) from t_item
      driver-class-name: com.mysql.cj.jdbc.Driver
      idle-timeout: 10000
      max-lifetime: 1800000
      initialization-fail-fast: true
      validation-timeout: 5000

  resources:
    cache-period: 7200
    chain:
      cache: true
      gzipped: true

logging:
  level:
    # com.yingtaohuo: DEBUG
    # org.springframework: DEBUG
    jooq: DEBUG