
app:
  site-url: http://127.0.0.1:8082

spring:
  freemarker:
    cache: false

logging:
  level:
    com.yingtaohuo: DEBUG
    # org.springframework: DEBUG
    org.jooq: DEBUG
    org.springframework.security: DEBUG