
app:
  sso-secret: eWluZ3Rhb2h1bw==
  cdn-url: https://file.menuxx.com

server:
  address: 0.0.0.0
  port: ${port:8082}
  context-path: /

spring:

  redis:
    database: 9
    host: yingtaohuo.com
    port: 7389
    password: 4cj34t4j9
    timeout: 1000
    pool:
      max-wait: 10000
      max-active: 50
      min-idle: 20
      max-idle: 30

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #password: FNQ31287twv
    #username: root
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:mysql://nizhuantech.com:65321/menuxx_prd?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    #type: com.zaxxer.hikari.HikariDataSource
    username: qurenjiadb
    password: 1s$kh8g!1
    url: jdbc:mysql://rm-uf68lsw07o293t779o.mysql.rds.aliyuncs.com/menuxx?characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 10
      connection-init-sql: select count(1) from t_item
      idle-timeout: 10000
      max-lifetime: 180000
      validation-timeout: 5000
      minimum-idle: 20
      connection-timeout: 6000

  freemarker:
    suffix: .ftl
    template-loader-path:
      - classpath:/views/
    cache: false

  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai

  devtools:
    livereload:
      enabled: true
    restart:
      trigger-file:

ronglian:
  app-id: 8a216da85da6adf7015de9addca8199f
  account-sid: 8a216da857511049015774861894153f
  auth-token: e1de26cde6e24dd28dfedcd81467d1f0

weixin:
  subscribe-no:
    app-id: wx0ab69ba942af8039
    app-secret: 4e1939ed22c63181c92d2fd2818cd6af
  service-no:
    app-id: wx931d9dfbd5275c6e
    app-secret: 5882869733213d929bee994933dae42b

qiniu:
  bucket: menuxx
  access-key: sr4H3rnxg3fkN9bf5NBTj9V9ptPFMnW5Ryxbg_o6
  secret-key: 9Gtvk0QbjvLDKWXwAi_WCYQkLq5Biu-X9wjHjXS5